# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: information_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'information_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19information_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcf\x01\n\x16GetInformationResponse\x12>\n\x0cuser_results\x18\x01 \x03(\x0b\x32(.GetInformationResponse.UserResultsEntry\x12\x1b\n\x13published_functions\x18\x02 \x03(\t\x12\x17\n\x0ftotal_scenarios\x18\x03 \x01(\x05\x1a?\n\x10UserResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.ResultList:\x02\x38\x01\"\x1c\n\nResultList\x12\x0e\n\x06values\x18\x01 \x03(\x01\x32W\n\x12InformationService\x12\x41\n\x0eGetInformation\x12\x16.google.protobuf.Empty\x1a\x17.GetInformationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'information_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETINFORMATIONRESPONSE_USERRESULTSENTRY']._loaded_options = None
  _globals['_GETINFORMATIONRESPONSE_USERRESULTSENTRY']._serialized_options = b'8\001'
  _globals['_GETINFORMATIONRESPONSE']._serialized_start=59
  _globals['_GETINFORMATIONRESPONSE']._serialized_end=266
  _globals['_GETINFORMATIONRESPONSE_USERRESULTSENTRY']._serialized_start=203
  _globals['_GETINFORMATIONRESPONSE_USERRESULTSENTRY']._serialized_end=266
  _globals['_RESULTLIST']._serialized_start=268
  _globals['_RESULTLIST']._serialized_end=296
  _globals['_INFORMATIONSERVICE']._serialized_start=298
  _globals['_INFORMATIONSERVICE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
