# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: function_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'function_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66unction_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x14GetFuncModelResponse\x12\x10\n\x08\x66unction\x18\x01 \x01(\t2R\n\x0f\x46unctionService\x12?\n\x0cGetFuncModel\x12\x16.google.protobuf.Empty\x1a\x15.GetFuncModelResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFUNCMODELRESPONSE']._serialized_start=55
  _globals['_GETFUNCMODELRESPONSE']._serialized_end=95
  _globals['_FUNCTIONSERVICE']._serialized_start=97
  _globals['_FUNCTIONSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
